'use client';

import { useEffect, useMemo, useState, useTransition } from 'react';
import { buildSeoPackage } from '@/lib/seo';
import type {
  MonetizationPreference,
  SeoPackage,
  UploadPayload,
  UploadResponse,
  VideoCategoryOption
} from '@/types';

const CATEGORY_LABELS: Record<VideoCategoryOption, string> = {
  tech: 'Tech',
  vlog: 'Vlog',
  shorts: 'Shorts',
  gaming: 'Gaming',
  tutorial: 'Tutorial'
};

const LANGUAGES = [
  'English',
  'Spanish',
  'Hindi',
  'Portuguese',
  'French',
  'German',
  'Japanese',
  'Korean',
  'Arabic'
];

type VideoSourceKind = 'file' | 'url';

const FALLBACK_SEO: SeoPackage = {
  title: 'Autogenerated YouTube Upload',
  description: 'This upload encountered an error before SEO metadata was generated.',
  hashtags: [],
  tags: [],
  thumbnailPrompt: 'Generate a default thumbnail with bold typography.',
  keywords: []
};

interface FormState {
  videoSourceKind: VideoSourceKind;
  videoFile: File | null;
  videoUrl: string;
  category: VideoCategoryOption;
  language: string;
  monetization: MonetizationPreference;
  scheduleEnabled: boolean;
  scheduleTime: string;
}

const INITIAL_FORM_STATE: FormState = {
  videoSourceKind: 'url',
  videoFile: null,
  videoUrl: '',
  category: 'tech',
  language: 'English',
  monetization: 'on',
  scheduleEnabled: false,
  scheduleTime: ''
};

function extractBaseName(kind: VideoSourceKind, file: File | null, url: string): string {
  if (kind === 'file' && file) {
    return file.name;
  }

  if (url) {
    try {
      const parsed = new URL(url);
      const segments = parsed.pathname.split('/').filter(Boolean);
      const lastSegment = segments.at(-1) ?? parsed.hostname;
      return lastSegment;
    } catch {
      return url;
    }
  }

  return '';
}

function formatDateTimeForDisplay(value?: string) {
  if (!value) return 'Immediate publish';
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return 'Immediate publish';
  return date.toLocaleString(undefined, {
    year: 'numeric',
    month: 'short',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit'
  });
}

export function UploadForm() {
  const [formState, setFormState] = useState<FormState>(INITIAL_FORM_STATE);
  const [seoPackage, setSeoPackage] = useState<SeoPackage | null>(null);
  const [uploadResponse, setUploadResponse] = useState<UploadResponse | null>(null);
  const [statusMessage, setStatusMessage] = useState<string>('');
  const [isUploading, startUploadTransition] = useTransition();

  const videoBaseName = useMemo(
    () => extractBaseName(formState.videoSourceKind, formState.videoFile, formState.videoUrl),
    [formState.videoFile, formState.videoSourceKind, formState.videoUrl]
  );

  useEffect(() => {
    if (!videoBaseName) {
      setSeoPackage(null);
      return;
    }

    const generated = buildSeoPackage({
      videoBaseName,
      category: formState.category,
      language: formState.language
    });
    setSeoPackage(generated);
  }, [videoBaseName, formState.category, formState.language]);

  const scheduleTime = formState.scheduleEnabled && formState.scheduleTime ? formState.scheduleTime : undefined;

  const payload: UploadPayload | null = useMemo(() => {
    if (!seoPackage || !videoBaseName) {
      return null;
    }

    return {
      videoSourceKind: formState.videoSourceKind,
      videoUrl: formState.videoSourceKind === 'url' ? formState.videoUrl.trim() : undefined,
      videoBaseName,
      category: formState.category,
      language: formState.language,
      monetization: formState.monetization,
      scheduleTime,
      seo: seoPackage
    };
  }, [seoPackage, videoBaseName, formState, scheduleTime]);

  async function handleUpload() {
    if (!payload) {
      setStatusMessage('Provide a valid video link or file to proceed.');
      return;
    }

    const formData = new FormData();
    formData.append('payload', JSON.stringify(payload));
    if (formState.videoSourceKind === 'file' && formState.videoFile) {
      formData.append('videoFile', formState.videoFile);
    }

    setStatusMessage('Uploading to YouTube…');
    setUploadResponse(null);

    try {
      const response = await fetch('/api/upload', {
        method: 'POST',
        body: formData
      });

      const data = (await response.json()) as UploadResponse;
      setUploadResponse(data);

      if (data.status === 'failed') {
        setStatusMessage(
          data.message ?? 'Upload failed. Verify credentials and try again.'
        );
      } else {
        setStatusMessage('Upload sequence completed.');
      }
    } catch (error) {
      const message =
        error instanceof Error ? error.message : 'Unexpected error while uploading.';
      setStatusMessage(message);
      setUploadResponse({
        status: 'failed',
        monetization: formState.monetization,
        seo: seoPackage ?? payload?.seo ?? FALLBACK_SEO,
        scheduleTime,
        message
      });
    }
  }

  const canSubmit =
    !!payload &&
    ((formState.videoSourceKind === 'file' && formState.videoFile) ||
      (formState.videoSourceKind === 'url' && formState.videoUrl.trim()));

  return (
    <div className="glass-panel grid" style={{ gap: '32px' }}>
      <header>
        <div className="status-pill" style={{ marginBottom: '16px' }}>
          Autonomous YouTube Upload Agent
        </div>
        <h1 style={{ fontSize: '2.2rem', fontWeight: 700, margin: '0 0 12px' }}>
          End-to-End YouTube Upload Automation
        </h1>
        <p className="muted">
          Provide the required publishing inputs. The agent builds SEO assets, optimizes metadata,
          and pushes the video live on YouTube with a single action.
        </p>
      </header>

      <section className="grid" style={{ gap: '18px' }}>
        <h2 className="section-heading">Publishing Inputs</h2>

        <div>
          <label className="field-label">
            Video Source
            <span className="muted">
              {formState.videoSourceKind === 'file' ? 'Upload local file' : 'Paste streaming link'}
            </span>
          </label>
          <div style={{ display: 'flex', gap: '12px', marginBottom: '12px', flexWrap: 'wrap' }}>
            <button
              type="button"
              onClick={() => setFormState((prev) => ({ ...prev, videoSourceKind: 'file' }))}
              className="button-primary"
              style={{
                background:
                  formState.videoSourceKind === 'file'
                    ? 'linear-gradient(135deg, #60a5fa, #34d399)'
                    : 'rgba(15, 23, 42, 0.65)',
                color: formState.videoSourceKind === 'file' ? '#0b1120' : '#cbd5f5'
              }}
            >
              Local File
            </button>
            <button
              type="button"
              onClick={() =>
                setFormState((prev) => ({
                  ...prev,
                  videoSourceKind: 'url',
                  videoFile: null
                }))
              }
              className="button-primary"
              style={{
                background:
                  formState.videoSourceKind === 'url'
                    ? 'linear-gradient(135deg, #60a5fa, #34d399)'
                    : 'rgba(15, 23, 42, 0.65)',
                color: formState.videoSourceKind === 'url' ? '#0b1120' : '#cbd5f5'
              }}
            >
              Remote Link
            </button>
          </div>
          {formState.videoSourceKind === 'file' ? (
            <input
              className="input"
              type="file"
              accept="video/*"
              onChange={(event) =>
                setFormState((prev) => ({
                  ...prev,
                  videoFile: event.target.files?.[0] ?? null
                }))
              }
            />
          ) : (
            <input
              className="input"
              type="url"
              placeholder="https://cdn.example.com/video.mp4"
              value={formState.videoUrl}
              onChange={(event) =>
                setFormState((prev) => ({
                  ...prev,
                  videoUrl: event.target.value
                }))
              }
            />
          )}
        </div>

        <div className="grid" style={{ gap: '16px' }}>
          <div>
            <label className="field-label">Category</label>
            <div style={{ display: 'flex', gap: '10px', flexWrap: 'wrap' }}>
              {(Object.keys(CATEGORY_LABELS) as VideoCategoryOption[]).map((category) => (
                <button
                  key={category}
                  type="button"
                  onClick={() => setFormState((prev) => ({ ...prev, category }))}
                  className="button-primary"
                  style={{
                    background:
                      formState.category === category
                        ? 'linear-gradient(135deg, #60a5fa, #34d399)'
                        : 'rgba(15, 23, 42, 0.65)',
                    color: formState.category === category ? '#0b1120' : '#cbd5f5'
                  }}
                >
                  {CATEGORY_LABELS[category]}
                </button>
              ))}
            </div>
          </div>

          <div>
            <label className="field-label">Language</label>
            <select
              className="input"
              value={formState.language}
              onChange={(event) =>
                setFormState((prev) => ({ ...prev, language: event.target.value }))
              }
            >
              {LANGUAGES.map((language) => (
                <option key={language} value={language}>
                  {language}
                </option>
              ))}
            </select>
          </div>

          <div>
            <label className="field-label">Monetization</label>
            <div style={{ display: 'flex', gap: '12px' }}>
              <button
                type="button"
                onClick={() => setFormState((prev) => ({ ...prev, monetization: 'on' }))}
                className="button-primary"
                style={{
                  background:
                    formState.monetization === 'on'
                      ? 'linear-gradient(135deg, #60a5fa, #34d399)'
                      : 'rgba(15, 23, 42, 0.65)',
                  color: formState.monetization === 'on' ? '#0b1120' : '#cbd5f5'
                }}
              >
                Enable Ads
              </button>
              <button
                type="button"
                onClick={() => setFormState((prev) => ({ ...prev, monetization: 'off' }))}
                className="button-primary"
                style={{
                  background:
                    formState.monetization === 'off'
                      ? 'linear-gradient(135deg, #60a5fa, #34d399)'
                      : 'rgba(15, 23, 42, 0.65)',
                  color: formState.monetization === 'off' ? '#0b1120' : '#cbd5f5'
                }}
              >
                Disable Ads
              </button>
            </div>
          </div>

          <div>
            <label className="field-label">Schedule</label>
            <div
              style={{
                display: 'flex',
                gap: '12px',
                alignItems: 'center',
                flexWrap: 'wrap'
              }}
            >
              <label style={{ display: 'inline-flex', alignItems: 'center', gap: '8px' }}>
                <input
                  type="checkbox"
                  checked={formState.scheduleEnabled}
                  onChange={(event) =>
                    setFormState((prev) => ({
                      ...prev,
                      scheduleEnabled: event.target.checked
                    }))
                  }
                />
                <span className="muted">Schedule publish time</span>
              </label>
              {formState.scheduleEnabled && (
                <input
                  className="input"
                  style={{ maxWidth: '260px' }}
                  type="datetime-local"
                  value={formState.scheduleTime}
                  onChange={(event) =>
                    setFormState((prev) => ({
                      ...prev,
                      scheduleTime: event.target.value
                    }))
                  }
                />
              )}
            </div>
          </div>
        </div>
      </section>

      <div className="divider" />

      <section className="grid" style={{ gap: '16px' }}>
        <h2 className="section-heading">SEO Blueprint</h2>
        {seoPackage ? (
          <>
            <div className="summary-card">
              <h3>SEO Title</h3>
              <p>{seoPackage.title}</p>
            </div>
            <div className="summary-card">
              <h3>SEO Description</h3>
              <p>{seoPackage.description}</p>
            </div>
            <div className="summary-card">
              <h3>Hashtags</h3>
              <ul>
                {seoPackage.hashtags.map((tag) => (
                  <li key={tag} className="tag">
                    {tag}
                  </li>
                ))}
              </ul>
            </div>
            <div className="summary-card">
              <h3>Video Tags</h3>
              <ul>
                {seoPackage.tags.map((tag) => (
                  <li key={tag} className="tag">
                    {tag}
                  </li>
                ))}
              </ul>
            </div>
            <div className="summary-card">
              <h3>Thumbnail Prompt</h3>
              <p>{seoPackage.thumbnailPrompt}</p>
            </div>
          </>
        ) : (
          <p className="muted">Provide a video file or link to auto-generate SEO metadata.</p>
        )}
      </section>

      <div className="divider" />

      <section className="grid" style={{ gap: '16px' }}>
        <button
          type="button"
          onClick={() =>
            startUploadTransition(() => {
              void handleUpload();
            })
          }
          className="button-primary"
          disabled={!canSubmit || isUploading}
          style={{ justifyContent: 'center', padding: '16px' }}
        >
          {isUploading ? (
            <>
              Uploading
              <span className="loading-dots" aria-hidden />
            </>
          ) : (
            'Generate SEO & Upload'
          )}
        </button>
        {statusMessage && <p className="muted">{statusMessage}</p>}
      </section>

      {uploadResponse && (
        <section className="grid" style={{ gap: '16px' }}>
          <h2 className="section-heading">Upload Summary</h2>
          <div className="summary-card">
            <h3>Video Title</h3>
            <p>{uploadResponse.seo.title}</p>
          </div>
          <div className="summary-card">
            <h3>Video Description</h3>
            <p>{uploadResponse.seo.description}</p>
          </div>
          <div className="summary-card">
            <h3>Tags</h3>
            <ul>
              {uploadResponse.seo.tags.map((tag) => (
                <li key={tag} className="tag">
                  {tag}
                </li>
              ))}
            </ul>
          </div>
          <div className="summary-card">
            <h3>Thumbnail Prompt</h3>
            <p>{uploadResponse.seo.thumbnailPrompt}</p>
          </div>
          <div className="summary-card">
            <h3>Scheduled Publish</h3>
            <p>{formatDateTimeForDisplay(uploadResponse.scheduleTime ?? uploadResponse.publishAt)}</p>
          </div>
          {uploadResponse.youtubeUrl && (
            <div className="summary-card">
              <h3>YouTube Link</h3>
              <p>
                <a href={uploadResponse.youtubeUrl} target="_blank" rel="noreferrer">
                  {uploadResponse.youtubeUrl}
                </a>
              </p>
            </div>
          )}
          {uploadResponse.message && (
            <div className="summary-card">
              <h3>Agent Notes</h3>
              <p>{uploadResponse.message}</p>
            </div>
          )}
        </section>
      )}
    </div>
  );
}
